### ISSUE TITLE
OpenAL

### ISSUE THREAD

**Issue by electroglyph** [electroglyph/vqisosmall#1]
VoxelQuest.exe currently needs openal32.dll to run, will be fixed shortly.

**Comment by gavanw** [comment]
Believe it can be found with SFML

**Comment by electroglyph** [comment]
sweet, you're right, can't test it right now tho cuz it was just my workstation where i needed it.  for some reason my laptop doesn't require it.

**Comment by electroglyph** [comment]
p.s.  doing about a dozen commits for each one i should really be doing, sorry! still getting the hang of things =)
